set(Plugin-ActivationPolicy "eager")
set(Plugin-Name "org.common.crypt")
set(Plugin-Version "1.0")
set(Plugin-Vendor "nriet")
set(Plugin-Description "encry the data")
set(Custom-Headers "Export-Interface")
set(Export-Interface "ICrypt")
